brewer.email.username=${BREWER_EMAIL_USERNAME:}
brewer.email.password=${BREWER_EMAIL_PASSWORD:}

spring.mvc.locale-resolve=fixed
spring.mvc.locale=pt_BR

spring.thymeleaf.mode=HTML

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/brewer-springboot?useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

localdate.format-pt_BR=dd/MM/yyyy
localdatetime.format-pt_BR=dd/MM/yyyy HH:mm
localtime.format-pt_BR=HH:mm

bigdecimal.format=#,##0.00
integer.format=#,##0

brewer.foto-storage-local.url-base=${BREWER_FOTO_STORAGE_LOCAL_URL_BASE:http://localhost:8080/fotos/}
brewer.foto-storage-local.local=${BREWER_FOTO_STORAGE_LOCAL_PATH:${user.home}/.brewerfotos}
